# Generated by Django 5.2.8 on 2025-12-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo_extra', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, to='pedidos.ingrediente'),
        ),
    ]
