"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv  # Para cargar variables de entorno desde un archivo .env
import dj_database_url  # Para gestionar la base de datos desde una URL

# Cargar variables del archivo .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# --------------------------
# 🔐 Seguridad y configuración
# --------------------------

SECRET_KEY = os.getenv("SECRET_KEY", "change-this")

DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Mis apps
    "rest_framework",
    "pedidos",
    "corsheaders",  # App que gestiona las cabeceras
    "django_filters",  # Filtros avanzados para DRF
]

MIDDLEWARE = [
    # IMPORTANTE: CorsMiddleware debe ir lo más arriba posible.
    # Debe interceptar la petición ANTES de que Django intente procesarla.
    # Si la pones al final, Django podría bloquear la petición antes de saber que es válida por CORS.
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# # Permitir todas las solicitudes CORS (no recomendado para producción)
# CORS_ALLOW_ALL_ORIGINS = True

# --------------------------
# CORS
# --------------------------

CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "False") == "True"


# CORS_ALLOW_ALL_ORIGINS = [
#     "http://localhost:3000",  # Permitir solicitudes desde este origen
#     "http://www.tu-dominio.com",  # Permitir solicitudes desde este dominio
# ]

# --------------------------
# Plantillas
# --------------------------

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# --------------------------
# Base de datos
# --------------------------

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    # Replace the SQLite DATABASES configuration with PostgreSQL:
    DATABASES = {
        "default": dj_database_url.config(
            # Replace this value with your local database's connection string.
            default=DATABASE_URL,
            conn_max_age=600,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# --------------------------
# Archivos estáticos
# --------------------------

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# This setting informs Django of the URI path from which your static files will be served to users
# Here, they well be accessible at your-domain.onrender.com/static/... or yourcustomdomain.com/static/...
STATIC_URL = "/static/"

# This production code might break development mode, so we check whether we're in DEBUG mode
if not DEBUG:
    # Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

    # Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
    # and renames the files with unique names for each version to support long-term caching
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Configuración de login
LOGIN_REDIRECT_URL = "menu"
LOGOUT_REDIRECT_URL = "menu"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # 1. JWT: Para la App Móvil / Postman (La prioridad)
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # 2. Session: Para que TÚ puedas navegar la API en el navegador (Browsable API)
        #    y para que el Admin siga funcionando integrado si fuera necesario.
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
    # Throttling (Límites de Peticiones)
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",  # Para anónimos
        "rest_framework.throttling.UserRateThrottle",  # Para logueados
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "10/minute",  # Anónimos: Solo 5 veces por minuto (Prueba agresiva)
        "user": "100/day",  # Usuarios: 100 al día
    },
    # Filtros
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    # 1. Clase de paginación
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    # 2. Tamaño de página por defecto
    "PAGE_SIZE": 5,  # Número de elementos por página
}
